name: "Pipeline"

on:
  pull_request: ## REQUIRED ON PULL REQUEST MERGES FOR BRANCHES IN BRANCH FLOW
    branches:
      - develop 
      - main
      - staging

  workflow_call:
    inputs: 
      version: # REQUIRED IF WORKFLOW_CALL IS USED
        description: 'The version to deploy'
        required: false
        type: string

    outputs:
      api:
        value: ${{ jobs.changes.outputs.api }}
      web:
        value: ${{ jobs.changes.outputs.web }}
      libs:
        value: ${{ jobs.changes.outputs.libs }}
      cicd:
        value: ${{ jobs.changes.outputs.cicd }}

  workflow_dispatch:
    inputs:
      version: # REQUIRED IF WORKFLOW_DISPATCH IS USED
        description: 'The version to deploy'
        required: false
        type: string

jobs:


  # =============================================================================
  # CHANGES DETECTION
  # =============================================================================
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/detect-changes
        with:
          baseRef: ${{ inputs.baseRef || 'main' }}

  # =============================================================================
  # TESTING JOBS
  # =============================================================================
  # Add your testing jobs here
  # Example:
  # test-api: 
  #   needs: branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test API
  #       run: |
  #         echo "Run API tests"
  #
  # test-web:
  #   needs: branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test Web
  #       run: |
  #         echo "Run Web tests"


  # =============================================================================
  # VERSIONING
  # =============================================================================
  version:
    ## COULD BE CHANGED TO IF: github.ref_name == 'develop'
    if: github.ref_name == 'develop'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/calculate-version
        with:
          baseRef: ${{ inputs.baseRef || 'main' }}


  # =============================================================================
  # DEPLOYMENT JOBS
  # =============================================================================
  # Add your deployment jobs here
  # Example:
  # deploy-api:
  #   ## COULD BE CHANGED TO IF: github.ref_name == 'develop'
  #   if: github.ref_name == 'develop'
  #   needs: branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy API
  #       run: |
  #         echo "Deploy API to production"
  #
  # deploy-web:
  #   ## COULD BE CHANGED TO IF: github.ref_name == 'develop'
  #   if: github.ref_name == 'develop'
  #   needs: branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy Web
  #       run: |
  #         echo "Deploy Web to production"
  #

  # =============================================================================
  # TAG & CREATE PR
  # =============================================================================     
  tag:
    ## COULD BE CHANGED TO IF: github.ref_name == 'develop'
    if: github.ref_name == 'develop'
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/create-tag
        with:
          version: ${{ needs.version.outputs.nextVersion }}


  createpr:
    ## SHOULD BE ANY BRANCH EXCEPT the final branch
    if: github.ref_name == 'develop' || github.ref_name == 'test' || github.ref_name == 'staging'
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/create-pr
        with:
          sourceBranch: ${{ github.ref_name }}
          targetBranch: 'main'
          title: 'Release ${{ needs.version.outputs.nextVersion }}'
          body: 'Automated release PR for version ${{ needs.version.outputs.nextVersion }}'
  

  branch:
    ## SHOULD BE THE NEXT BRANCH

    needs: createpr
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/manage-branch
        with:
          action: 'fast-forward'
          targetBranch: 'main'
          sourceBranch: ${{ github.ref_name }}
