name: "Changes"

on:
  workflow_call:
    outputs:
      api: 
        value: ${{ jobs.changes.outputs.api }}
      web: 
        value: ${{ jobs.changes.outputs.web }}
      docs: 
        value: ${{ jobs.changes.outputs.docs }}
      libs: 
        value: ${{ jobs.changes.outputs.libs }}
      cicd:
        value: ${{ jobs.changes.outputs.cicd }}
      
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      api: ${{ steps.merge.outputs.api }}
      web: ${{ steps.merge.outputs.web }}
      docs: ${{ steps.merge.outputs.docs }}
      libs: ${{ steps.merge.outputs.libs }}
      cicd: ${{ steps.merge.outputs.cicd }}
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Base Branch
      id: set-base
      ## if base branch is develop compare to test.  Test and Main always fully deploy
      run: |
        base_branch=$(
          if [[ '${{ github.ref }}' == 'refs/heads/develop' ]]; then
            echo 'test'
          else
            echo 'develop'
          fi
        )
        echo "Base branch determined: $base_branch"
        echo "base_branch=$base_branch" >> $GITHUB_ENV

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ env.base_branch }}
        filters: |
          api:
            - 'apps/api/**'
          web:
            - 'apps/interfaces/web/**'
          docs:
            - 'apps/docs/**'
          libs:
            - 'libs/**'
          cicd: 
            - '.github/workflows/**'

    - name: Merge filter outputs with branch condition
      id: merge
      run: |
        echo "api=${{ steps.filter.outputs.api == 'true' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' }}" >> $GITHUB_OUTPUT
        echo "web=${{ steps.filter.outputs.web == 'true' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' }}" >> $GITHUB_OUTPUT
        echo "docs=${{ steps.filter.outputs.docs == 'true' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' }}" >> $GITHUB_OUTPUT
        echo "libs=${{ steps.filter.outputs.libs == 'true' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' }}" >> $GITHUB_OUTPUT
        echo "cicd=${{ steps.filter.outputs.cicd == 'true' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' }}" >> $GITHUB_OUTPUT

    - name: Debug Paths Filter Outputs
      run: |
        echo "API: ${{ steps.merge.outputs.api }}"
        echo "WEB: ${{ steps.merge.outputs.web }}"
        echo "DOCS: ${{ steps.merge.outputs.docs }}"
        echo "LIBS: ${{ steps.merge.outputs.libs }}"
        echo "CICD: ${{ steps.merge.outputs.cicd }}"