name: "Pipeline"
# Test change for deploy flow validation
run-name: "Pipeline: ${{ github.ref_name }} ${{ inputs.version && format('({0})', inputs.version) || '' }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to deploy
        required: false
        type: string
      baseRef:
        description: The base reference for comparison
        required: false
        type: string
  push:
    branches:
      - develop
      - staging
      - main
jobs:

  
  #=============================================================================
  # CHANGES DETECTION
  #=============================================================================
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ inputs.baseRef || 'main' }}
          filters: |
            core:
              - 'src/**'
            test:
              - 'tests/**'
            cicd:
              - '.github/**'
    outputs:
      cicd: ${{ steps.filter.outputs.cicd }}
      core: ${{ steps.filter.outputs.core }}
      test: ${{ steps.filter.outputs.test }}

  #=============================================================================
  # TESTING JOBS
  #=============================================================================
  test-cicd:
    needs: changes
    if: ${{ needs.changes.outputs.cicd == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # TODO: Replace with your cicd test logic
      - name: Run cicd tests
        run: |
          echo "Running tests for cicd domain"
          echo "Replace this with your actual test commands"
          # Example: npm test -- --testPathPattern=cicd

  test-core:
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # TODO: Replace with your core test logic
      - name: Run core tests
        run: |
          echo "Running tests for core domain"
          echo "Replace this with your actual test commands"
          # Example: npm test -- --testPathPattern=core

  test-test:
    needs: changes
    if: ${{ needs.changes.outputs.test == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # TODO: Replace with your test test logic
      - name: Run test tests
        run: |
          echo "Running tests for test domain"
          echo "Replace this with your actual test commands"
          # Example: npm test -- --testPathPattern=test

  #=============================================================================
  # VERSIONING
  #=============================================================================
  version:
    if: ${{
        always() &&
        (
        needs.test-cicd.result != 'failure' &&
        needs.test-core.result != 'failure' &&
        needs.test-test.result != 'failure'
      ) &&
        (
        needs.test-cicd.result == 'success' ||
        needs.test-core.result == 'success' ||
        needs.test-test.result == 'success'
      )
      }}
    needs: [ changes, test-cicd, test-core, test-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/calculate-version
        id: version
        with:
          baseRef: ${{ inputs.baseRef || 'main' }}
    outputs:
      version: ${{ steps.version.outputs.version }}

  #=============================================================================
  # DEPLOYMENT JOBS
  #=============================================================================
  deploy-core:
    needs: [ version, changes ]
    if: ${{ fromJSON(needs.changes.outputs.core) }}
    runs-on: ubuntu-latest
    steps:
      # TODO: Replace with your test test logic
      - name: Deploy core
        run: |
          echo "Deploying core"
          echo "Replace this with your actual deploy commands"
          # Example: npm deploy -- --testPathPattern=core

  #=============================================================================
  # REMOTE TESTING JOBS
  #=============================================================================
  remote-test-core:
    needs: [ deploy-core, changes ]
    if: ${{ fromJSON(needs.changes.outputs.core) }}
    runs-on: ubuntu-latest
    steps:
      # TODO: Replace with your test test logic
      - name: Test core
        run: |
          echo "Testing core remotely"
          echo "Replace this with your actual test commands"
          # Example: npm test -- --testPathPattern=core

  #=============================================================================
  # TAG & PROMOTE
  #=============================================================================
  tag:
    # Needs all deploy and/or remote test jobs to succeed or be skipped
    # Needs at least one domain to succeed
    needs: [ version, deploy-core, remote-test-core ]
    if: ${{
        always() &&
        github.ref_name == 'develop' &&
        (
        needs.deploy-core.result != 'failure' &&
        needs.remote-test-core.result != 'failure'
      ) &&
        (
        needs.deploy-core.result == 'success' ||
        needs.remote-test-core.result == 'success'
      )
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/create-tag
        with:
          version: ${{ needs.version.outputs.version }}

  #=============================================================================
  # PROMOTION JOB
  #=============================================================================
  promote:
    # Only runs on push or manual workflow_dispatch events to branches that can promote
    # Waits for version/tag if they run, but doesn't fail if they're skipped
    # Needs all deploy and/or remote test jobs to succeed
    if: ${{
        always() &&
        (
        github.event_name == 'push' ||
        github.event_name == 'workflow_dispatch'
      ) &&
        (
        needs.tag.result == 'success' ||
        needs.tag.result == 'skipped'
      ) &&
        (
        github.ref_name == 'develop' ||
        github.ref_name == 'staging'
      )
      }}
    needs: [ tag ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/promote-branch
        with:
          sourceBranch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
