## USER COMMENT 1

name: "USER NAME"
# USER COMMENT 2
on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.tsx'
    # USER COMMENT 3
    branches:
      - develop
      - feature
      - staging
      - main
      # USER COMMENT 4

  workflow_call:
    inputs:
      # USER COMMENT 5
      fakevar1:
        description: 'The fake version to deploy'
        required: false
        type: string
      version:
        description: The version to deploy
        required: false
        type: string
      # USER COMMENT 7
      fakevar2:
        description: 'The fake version to deploy'
        required: false
        type: string
      baseRef:
        description: The base reference for comparison
        required: false
        type: string
    # USER COMMENT 8
    outputs:
      fakevar3:
        value: 'fakevalue3'
      fakevar4:
        value: 'fakevalue4'
  workflow_dispatch:
    inputs:
      version:
        description: The version to deploy
        required: false
        type: string
      baseRef:
        description: The base reference for comparison
        required: false
        type: string

jobs:
  # USER COMMENT 9

  fake-job-1:
    # USER COMMENT 10    
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"

  # =============================================================================
  # CHANGES DETECTION
  # =============================================================================
  # USER COMMENT 11
  changes:
    items:
      - key:
          # =============================================================================
          # CHANGES DETECTION
          # =============================================================================
          runs-on
        value: ubuntu-latest
      - key: steps
        value:
          items:
            - items:
                - key: uses
                  value: ./.github/actions/detect-changes
                - key: with
                  value:
                    items:
                      - key: baseRef
                        value: "{ inputs.baseRef || main "
                    range:
                      - 334
                      - 370
                      - 370
              range:
                - 263
                - 370
                - 370
          range:
            - 261
            - 370
            - 370
    range:
      - 213
      - 370
      - 370

  # USER COMMENT 12
  fake-job-2:
    # USER COMMENT 13
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"

  # =============================================================================
  # TESTING JOBS
  # =============================================================================
  # Add your testing jobs here
  # Example:
  # test-api: 
  #   needs: branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test API
  #       run: |
  #         echo "Run API tests"
  #
  # test-web:
  #   needs: branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test Web
  #       run: |
  #         echo "Run Web tests"


  # USER COMMENT 14

  fake-job-3:
    # USER COMMENT 15
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"

  # =============================================================================
  # VERSIONING
  # =============================================================================
  version:
    items:
      - key:
          # =============================================================================
          # VERSIONING
          # =============================================================================
          if
        value: github.ref_name == 'develop'
      - key: needs
        value: changes
      - key: runs-on
        value: ubuntu-latest
      - key: steps
        value:
          items:
            - items:
                - key: uses
                  value: ./.github/actions/calculate-version
                - key: with
                  value:
                    items:
                      - key: baseRef
                        value: "{ inputs.baseRef || 'main' "
                    range:
                      - 394
                      - 432
                      - 432
              range:
                - 320
                - 432
                - 432
          range:
            - 318
            - 432
            - 432
    range:
      - 206
      - 432
      - 432

  # USER COMMENT 16

  fake-job-4:
    # USER COMMENT 17
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"

  # USER COMMENT 18

  fake-job-5:
    # USER COMMENT 19
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"

  # USER COMMENT 20

  # =============================================================================
  # DEPLOYMENT JOBS
  # =============================================================================
  deploy-api:
    needs: branch
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API
        run: |
          echo "Deploy API to production"

  fake-job-6:
    # USER COMMENT 21
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"

  # =============================================================================
  # TAG & CREATE PR
  # =============================================================================     
  tag:
    items:
      - key:
          # =============================================================================
          # TAG & CREATE PR
          # =============================================================================
          if
        value: github.ref_name == 'develop'
      - key: needs
        value: version
      - key: runs-on
        value: ubuntu-latest
      - key: steps
        value:
          items:
            - items:
                - key: uses
                  value: ./.github/actions/create-tag
                - key: with
                  value:
                    items:
                      - key: version
                        value: "{ needs.version.outputs.nextVersion "
                    range:
                      - 392
                      - 439
                      - 439
              range:
                - 325
                - 439
                - 439
          range:
            - 323
            - 439
            - 439
    range:
      - 211
      - 439
      - 439

  # USER COMMENT 22

  fake-job-7:
    # USER COMMENT 23
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"

  createpr:
    items:
      - key:
          ## SHOULD BE ANY BRANCH EXCEPT the final branch
          if
        value: github.ref_name != 'main'
      - key: needs
        value: tag
      - key: runs-on
        value: ubuntu-latest
      - key: steps
        value:
          items:
            - items:
                - key: uses
                  value: ./.github/actions/create-pr
                - key: with
                  value:
                    items:
                      - key: sourceBranch
                        value: "{ github.ref_name "
                    range:
                      - 238
                      - 272
                      - 272
              range:
                - 172
                - 272
                - 272
          range:
            - 170
            - 272
            - 272
    range:
      - 65
      - 272
      - 272

  branch:
    items:
      - key:
          ## SHOULD BE THE NEXT BRANCH
          needs
        value: createpr
      - key: runs-on
        value: ubuntu-latest
      - key: steps
        value:
          items:
            - items:
                - key: uses
                  value: ./.github/actions/manage-branch
                - key: with
                  value:
                    items:
                      - key: action
                        value: 'fast-forward'
                      - key: targetBranch
                        value: "{ github.ref_name == 'develop' && 'staging' || github.ref_name ==
                          'staging' && 'main' || github.ref_name == 'main' &&
                          'main' || 'main' "
                    range:
                      - 190
                      - 378
                      - 378
              range:
                - 120
                - 378
                - 378
          range:
            - 118
            - 378
            - 378
    range:
      - 46
      - 378
      - 378

  # USER COMMENT 24

  fake-job-8:
    # USER COMMENT 25
    runs-on: ubuntu-latest
    steps:
      - name: Fake Job
        run: |
          echo "Running fake job"
