name: "Pipeline"

on:
  workflow_call:
    inputs:
      version:
        description: 'The version to deploy'
        required: false
        type: string
    outputs:
      api: 
        value: ${{ jobs.changes.outputs.api }}
      web: 
        value: ${{ jobs.changes.outputs.web }}
      libs: 
        value: ${{ jobs.changes.outputs.libs }}
      cicd: 
        value: ${{ jobs.changes.outputs.cicd }}
      
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: false
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/job._changes
        with:
          baseRef: ${{ inputs.baseRef || 'main' }}

  version:
    if: github.ref_name == 'develop'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/job._version
        with:
          baseRef: ${{ inputs.baseRef || 'main' }}

  tag:
    if: github.ref_name == 'develop'
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/job._tag
        with:
          version: ${{ needs.version.outputs.nextVersion }}

  createpr:
    if: github.ref_name == 'develop'
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/job._createpr
        with:
          sourceBranch: ${{ github.ref_name }}
          targetBranch: 'main'
          title: 'Release ${{ needs.version.outputs.nextVersion }}'
          body: 'Automated release PR for version ${{ needs.version.outputs.nextVersion }}'

  branch:
    if: github.ref_name == 'develop'
    needs: createpr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/job._branch
        with:
          action: 'fast-forward'
          targetBranch: 'main'
          sourceBranch: ${{ github.ref_name }}

  apps:
    if: github.ref_name == 'develop'
    needs: branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/job._apps
        with:
          environment: 'production'
          domains: 'api,web,libs'
          version: ${{ needs.version.outputs.nextVersion }}