name: "Pipeline"

on:
  workflow_call:
    inputs:
      version:
        description: 'The version to deploy'
        required: false
        type: string
    outputs:
      api: 
        value: ${{ jobs.changes.outputs.api }}
      web: 
        value: ${{ jobs.changes.outputs.web }}
      libs: 
        value: ${{ jobs.changes.outputs.libs }}
      cicd: 
        value: ${{ jobs.changes.outputs.cicd }}
      
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: false
        type: string

jobs:
  changes:
    uses: ./.github/workflows/job._changes.yml
    secrets: inherit

  version:
    if: github.ref_name == 'develop'
    needs: changes
    uses: ./.github/workflows/job._version.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  tag:
    if: github.ref_name == 'develop'
    needs: version
    uses: ./.github/workflows/job._tag.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  createpr:
    if: github.ref_name == 'develop'
    needs: tag
    uses: ./.github/workflows/job._createpr.yml
    secrets: inherit

  branch:
    if: github.ref_name == 'develop'
    needs: createpr
    uses: ./.github/workflows/job._branch.yml
    secrets: inherit

  apps:
    if: github.ref_name == 'develop'
    needs: branch
    uses: ./.github/workflows/job._apps.yml
    secrets: inherit