name: "Test Actions Simple"

on:
  push:
    branches: [ main, develop ]

jobs:
  test-detect-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Detect Changes Action
        uses: ./.github/actions/detect-changes
        with:
          baseRef: 'main'

  test-calculate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Calculate Version Action
        uses: ./.github/actions/calculate-version
        with:
          baseRef: 'main'

  test-create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Create Tag Action
        uses: ./.github/actions/create-tag
        with:
          version: '1.0.0-test'
          tag_prefix: 'v'
          push: 'false'

  test-deploy-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Deploy Apps Action
        uses: ./.github/actions/deploy-apps
        with:
          environment: 'development'
          domains: 'api,web'
          version: '1.0.0-test'
