name: Test Actions
on:
  push:
    branches: [main]

jobs:
  test-calculate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Calculate Version Action
        uses: ./.github/actions/calculate-version
        with:
          base_branch: main

  test-detect-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Detect Changes Action
        uses: ./.github/actions/detect-changes
        with:
          base_branch: main
